#!/bin/bash

# This bash script should get a newly-imaged machine up-and-running

# Make the file executable
chmod u+x initial_build_script

# Update package list, and upgrade packages where applicable
sudo apt-get update
sudo apt-get upgrade

# Install my standard suite of packages
sudo apt-get install fish omf i3 i3-wm i3blocks i3status i3lock feh xrandr lxappearance thunar gnome-icon-theme-full rofi compton git ruby python bpython rvm atom autoconf automake pkg-config libgtk-3-dev

# CONFIG FILES:
# 1. Clone dotfiles repo to ~/Documents/
git clone https://github.com/BBagTP/dotfiles.git ~/Documents/
# 2. Copy files from cloned git repo to their respective folders
cp ~/Documents/dotfiles/vim/.vimrc ~/
cp -r ~/Documents/dotfiles/vim/.vim/ ~/
cp ~/Documents/dotfiles/i3/config ~/.config/i3/
cp ~/Documents/dotfiles/i3/config ~/.config/i3/
cp -r ~/Documents/dotfiles/.fonts ~/

# Download a wallpaper that i3 will use on startup
mkdir ~/Pictures/wallpaper
wget -p ~/Pictures/wallpaper/ -o wallpaper.jpg http://wallpaperstock.net/the-road-so-far..._wallpapers_27129_2560x1440.jpg

# Arc themes
# GTK theme:
git clone https://github.com/horst3180/arc-theme --depth=1
cd arc-theme
./autogen.sh --prefix=/usr
sudo make install

# Install powerline fonts
git clone https://github.com/powerline/fonts.git --depth=1
cd fonts
./install.#!/bin/sh
cd ..
rm -rf fonts

# Download FontAwesome
wget -p ~/Downloads/ -o font-awesome.zip https://github.com/FortAwesome/Font-Awesome/archive/v4.7.0.zip
unzip font-awesome.zip
cd font-awesome/
cp *.ttf /etc/share/fonts/

# Sets fish-shell as the default shell, and installs the bobthefish theme
chsh -s /usr/local/bin/fish
omf install bobthefish

#Final message
echo "Things you will need to do manually:"
echo " - Open lxapperance, set system font to 'SFNS Display'"
echo " - Visit https://addons.mozilla.org/en/firefox/collections/horst3180/a/ \n for arc-firefox theme"
